### ISSUE TITLE
EVAManager breaks Rescue Kerbal contracts

### ISSUE THREAD

**Issue by dewiniaid** [toadicus/EVAManager#1]
While attempting to do a series of 'Rescue Soandso Kerman, who is stranded in orbit' contracts, I discovered that the kerbals in question start with 0 EVA Propellant... and this was not solved by having them re-enter the pod they started with.  

Removing EVA Manager seems to have fixed this for the remaining contracts (which I hadn't accepted yet prior to its removal).

**Comment by toadicus** [comment]
Dewiniaid, take a look in your EVAManager folder and delete or rename EVAManager.cfg to any other extension.  Latest versions of EVAManager should be distributing it as EVAManager.cfg.example for that specific reason.

EVAManager.cfg is basically a "proof of concept" patch that introduces a requirement to track EVA Propellant for entire missions instead of individual jaunts.  Its relationship to recovery contracts is something I need to look in to more before I recommend that people use it... but I think it's fun.  Recovery contracts _are_ still possible, they're just a lot harder to do. :)

**Comment by toadicus** [comment]
This was fixed by db93e424.
